export const JOB_TITLE = [
  "BACKEND_DEVELOPER",
  "FRONTEND_DEVELOPER",
  "FULLSTACK_DEVELOPER",
  "MOBILE_DEVELOPER",
  "ANDROID_DEVELOPER",
  "IOS_DEVELOPER",
  "DATA_SCIENCE",
  "DATA_ANALYST",
  "DATA_ENGINEER",
  "DATA_ARCHITECT",
  "DATA_SCIENTIST"
];
