spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}


github:
  api-url: https://api.github.com
  token: ${GITHUB_API_TOKEN}
  client-id: ${GITHUB_CLIENT_ID}
  client-secret: ${GITHUB_CLIENT_SECRET}
  authorize-url: https://github.com/login/oauth/authorize
  access-token-url: https://github.com/login/oauth/access_token
  html-url: https://github.com/
  redirect_uri: ${GITHUB_REDIRECT_URI}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  api-url: https://www.googleapis.com
  authorize-url: https://accounts.google.com/o/oauth2/v2/auth
  access-token-url: https://accounts.google.com/o/oauth2/token
  redirect-uri: ${GOOGLE_REDIRECT_URI}
  token-url: https://oauth2.googleapis.com/tokeninfo


jwt:
  key: ${JWT_KEY}

allowed-origins: ${ALLOWED_ORIGINS}
